[theme]
base = "light"
primaryColor = "#426f3c"
backgroundColor = "#fcf6e7"
secondaryBackgroundColor = "#e4edcf"
textColor = "#243c2b"
font = "monospace"

[browser]
gatherUsageStats = false

[server]
headless = true
